version: "3.7"

services:
  strapi:
    build: .
    image: strapi/strapi:latest
    container_name: strapi
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: /srv/app/data/db.sqlite
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./config:/srv/app/config
      - ./src:/srv/app/src
      - ./data:/srv/app/data
      - ./public/uploads:/srv/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi
    labels:
      - "traefik.enable=true"
      # Rules for Strapi API and Admin
      - "traefik.http.routers.strapi-router.rule=Host(`api.hadaphoto.hu`)"
      - "traefik.http.routers.strapi-router.entrypoints=websecure"
      - "traefik.http.routers.strapi-router.tls.certresolver=myresolver"
      - "traefik.http.services.strapi-service.loadbalancer.server.port=1337"
      - "traefik.http.services.strapi-service.loadbalancer.server.scheme=http"
      - "traefik.http.services.strapi-service.loadbalancer.healthcheck.path=/"
      - "traefik.http.services.strapi-service.loadbalancer.healthcheck.interval=30s"
      - "traefik.http.services.strapi-service.loadbalancer.server.forwardedHeaders.insecure=true"
      - "traefik.http.routers.strapi-router.tls=true"
      - "traefik.http.services.strapi-service.loadbalancer"
      - "traefik.http.routers.strapi-router.service=strapi-service"
      - "traefik.http.services.strapi-service.loadbalancer.sticky.cookie.secure=true"
      - "traefik.http.services.strapi-service.loadbalancer.sticky.cookie.httpOnly=true"
      - "traefik.http.services.strapi-service.loadbalancer.sticky.cookie.sameSite=lax"

  reverse-proxy:
    image: traefik:v2.5
    container_name: reverse-proxy
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=sajtos0007@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.hadaphoto.hu`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"

networks:
  strapi:
    driver: bridge
