version: "3.7"

services:
  strapi:
    image: strapi/strapi:latest
    container_name: strapi
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: ./data/db.sqlite
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./data:/opt/app/data
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi
    labels:
      - "traefik.enable=true"
      # Rules for Strapi API
      - "traefik.http.routers.strapi-api-router.rule=Host(`api.hadaphoto.hu`)"
      - "traefik.http.routers.strapi-api-router.entrypoints=websecure"
      - "traefik.http.routers.strapi-api-router.tls.certresolver=myresolver"
      - "traefik.http.services.strapi-api-service.loadbalancer.server.port=1337"
      - "traefik.http.routers.strapi-api-router.service=strapi-api-service"
      - "traefik.http.routers.strapi-api-router.tls=true"
      - "traefik.http.routers.strapi-api-service=noop@internal"
      # Rules for Strapi Admin
      - "traefik.http.routers.strapi-admin-router.rule=Host(`admin.hadaphoto.hu`)"
      - "traefik.http.routers.strapi-admin-router.entrypoints=websecure"
      - "traefik.http.routers.strapi-admin-router.tls.certresolver=myresolver"
      - "traefik.http.services.strapi-admin-service.loadbalancer.server.port=1337"
      - "traefik.http.routers.strapi-admin-router.service=strapi-admin-service"
      - "traefik.http.middlewares.strapi-admin-replacepathregex.regex=^/admin/(.*)"
      - "traefik.http.middlewares.strapi-admin-replacepathregex.replacement=/\\$${1}"
      - "traefik.http.routers.strapi-admin-router.middlewares=strapi-admin-replacepathregex"
      - "traefik.http.routers.strapi-admin-router.tls=true"
      - "traefik.http.routers.strapi-admin-service=noop@internal"

  reverse-proxy:
    image: traefik:v2.5
    container_name: reverse-proxy
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=sajtos0007@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.hadaphoto.hu`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"

networks:
  strapi:
    driver: bridge